# Site settings
title: Wut?
author:
  name: Craig Foote
  email: CraigFoote@gmail.com
description: "Careful. I don't know wwhat I'm doing."

# Build settings
remote_theme: sujaykundu777/devlopr-jekyll
